// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"database/sql"
	"time"
)

type Enclosure struct {
	ID   int64
	Name string
}

type EnclosureAirHumidity struct {
	ID          int64
	Timestamp   sql.NullTime
	EnclosureID int64
	HumidityRh  float64
}

type EnclosureAirTemperature struct {
	ID           int64
	Timestamp    sql.NullTime
	EnclosureID  int64
	TemperatureC float64
}

type EnclosureNote struct {
	ID        int64
	Timestamp sql.NullTime
	Content   sql.NullString
}

type Flow struct {
	ID           int64
	Name         string
	SystemID     int64
	ParentFlowID sql.NullInt64
}

type FlowNote struct {
	ID        int64
	Timestamp sql.NullTime
	Content   sql.NullString
}

type FlowRate struct {
	ID        int64
	FlowID    int64
	Timestamp sql.NullTime
	RateMps   float64
}

type Plant struct {
	ID          int64
	PlantSiteID int64
	PlantedOn   sql.NullTime
	SpeciesID   sql.NullInt64
}

type PlantGenu struct {
	ID   int64
	Name string
}

type PlantNote struct {
	ID        int64
	PlanID    sql.NullInt64
	Timestamp time.Time
	Content   sql.NullString
}

type PlantSite struct {
	ID     int64
	FlowID int64
	X      int64
	Y      int64
	Z      int64
}

type PlantSiteLux struct {
	ID          int64
	PlantSiteID int64
	Timestamp   sql.NullTime
	Lux         int64
}

type PlantSiteNote struct {
	ID          int64
	PlantSiteID int64
	Timestamp   time.Time
	Content     sql.NullString
}

type PlantSpecy struct {
	ID           int64
	Name         string
	PlantGenusID sql.NullInt64
}

type System struct {
	ID          int64
	Name        string
	EnclosureID int64
}

type SystemEc struct {
	ID        int64
	SystemID  int64
	Timestamp sql.NullTime
	Ec        float64
}

type SystemNote struct {
	ID        int64
	Timestamp sql.NullTime
	Content   sql.NullString
}

type SystemOxygen struct {
	ID        int64
	SystemID  int64
	Timestamp sql.NullTime
	Oxygen    float64
}

type SystemPh struct {
	ID        int64
	SystemID  int64
	Timestamp sql.NullTime
	Ph        float64
}

type SystemWaterProximity struct {
	ID         int64
	SystemID   int64
	Timestamp  sql.NullTime
	ProximityM float64
}

type SystemWaterTemperature struct {
	ID                int64
	SystemID          int64
	Timestamp         sql.NullTime
	WaterTemperatureC float64
}
