// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const createEnclosure = `-- name: CreateEnclosure :one
INSERT INTO enclosure (name)
VALUES (?)
RETURNING id, name
`

func (q *Queries) CreateEnclosure(ctx context.Context, name string) (Enclosure, error) {
	row := q.db.QueryRowContext(ctx, createEnclosure, name)
	var i Enclosure
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createEnclosureAirHumidity = `-- name: CreateEnclosureAirHumidity :exec
INSERT INTO enclosure_air_humidity (enclosure_id, humidity_rh)
VALUES (?, ?)
`

type CreateEnclosureAirHumidityParams struct {
	EnclosureID int64
	HumidityRh  float64
}

func (q *Queries) CreateEnclosureAirHumidity(ctx context.Context, arg CreateEnclosureAirHumidityParams) error {
	_, err := q.db.ExecContext(ctx, createEnclosureAirHumidity, arg.EnclosureID, arg.HumidityRh)
	return err
}

const createEnclosureAirTemperature = `-- name: CreateEnclosureAirTemperature :exec
INSERT INTO enclosure_air_temperature (enclosure_id, temperature_c)
VALUES (?, ?)
`

type CreateEnclosureAirTemperatureParams struct {
	EnclosureID  int64
	TemperatureC float64
}

func (q *Queries) CreateEnclosureAirTemperature(ctx context.Context, arg CreateEnclosureAirTemperatureParams) error {
	_, err := q.db.ExecContext(ctx, createEnclosureAirTemperature, arg.EnclosureID, arg.TemperatureC)
	return err
}

const createEnclosureNote = `-- name: CreateEnclosureNote :one
INSERT INTO enclosure_note (timestamp, content)
VALUES (?, ?)
RETURNING id, timestamp, content
`

type CreateEnclosureNoteParams struct {
	Timestamp sql.NullTime
	Content   sql.NullString
}

func (q *Queries) CreateEnclosureNote(ctx context.Context, arg CreateEnclosureNoteParams) (EnclosureNote, error) {
	row := q.db.QueryRowContext(ctx, createEnclosureNote, arg.Timestamp, arg.Content)
	var i EnclosureNote
	err := row.Scan(&i.ID, &i.Timestamp, &i.Content)
	return i, err
}

const createFlow = `-- name: CreateFlow :one
INSERT INTO flow (name, system_id, parent_flow_id)
VALUES (?, ?, ?)
RETURNING id, name, system_id, parent_flow_id
`

type CreateFlowParams struct {
	Name         string
	SystemID     int64
	ParentFlowID sql.NullInt64
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, createFlow, arg.Name, arg.SystemID, arg.ParentFlowID)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SystemID,
		&i.ParentFlowID,
	)
	return i, err
}

const createFlowNote = `-- name: CreateFlowNote :one
INSERT INTO flow_note (timestamp, content)
VALUES (?, ?)
RETURNING id, timestamp, content
`

type CreateFlowNoteParams struct {
	Timestamp sql.NullTime
	Content   sql.NullString
}

func (q *Queries) CreateFlowNote(ctx context.Context, arg CreateFlowNoteParams) (FlowNote, error) {
	row := q.db.QueryRowContext(ctx, createFlowNote, arg.Timestamp, arg.Content)
	var i FlowNote
	err := row.Scan(&i.ID, &i.Timestamp, &i.Content)
	return i, err
}

const createFlowRate = `-- name: CreateFlowRate :exec
INSERT INTO flow_rate (flow_id, rate_mps)
VALUES (?, ?)
`

type CreateFlowRateParams struct {
	FlowID  int64
	RateMps float64
}

func (q *Queries) CreateFlowRate(ctx context.Context, arg CreateFlowRateParams) error {
	_, err := q.db.ExecContext(ctx, createFlowRate, arg.FlowID, arg.RateMps)
	return err
}

const createPlant = `-- name: CreatePlant :one
INSERT INTO plant (plant_site_id, planted_on, species_id)
VALUES (?, ?, ?)
RETURNING id, plant_site_id, planted_on, species_id
`

type CreatePlantParams struct {
	PlantSiteID int64
	PlantedOn   sql.NullTime
	SpeciesID   sql.NullInt64
}

func (q *Queries) CreatePlant(ctx context.Context, arg CreatePlantParams) (Plant, error) {
	row := q.db.QueryRowContext(ctx, createPlant, arg.PlantSiteID, arg.PlantedOn, arg.SpeciesID)
	var i Plant
	err := row.Scan(
		&i.ID,
		&i.PlantSiteID,
		&i.PlantedOn,
		&i.SpeciesID,
	)
	return i, err
}

const createPlantGenus = `-- name: CreatePlantGenus :one
INSERT INTO plant_genus (name)
VALUES (?)
RETURNING id, name
`

func (q *Queries) CreatePlantGenus(ctx context.Context, name string) (PlantGenu, error) {
	row := q.db.QueryRowContext(ctx, createPlantGenus, name)
	var i PlantGenu
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createPlantNote = `-- name: CreatePlantNote :one
INSERT INTO plant_note (plan_id, timestamp, content)
VALUES (?, ?, ?)
RETURNING id, plan_id, timestamp, content
`

type CreatePlantNoteParams struct {
	PlanID    sql.NullInt64
	Timestamp time.Time
	Content   sql.NullString
}

func (q *Queries) CreatePlantNote(ctx context.Context, arg CreatePlantNoteParams) (PlantNote, error) {
	row := q.db.QueryRowContext(ctx, createPlantNote, arg.PlanID, arg.Timestamp, arg.Content)
	var i PlantNote
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Timestamp,
		&i.Content,
	)
	return i, err
}

const createPlantSite = `-- name: CreatePlantSite :one
INSERT INTO plant_site (flow_id, x, y, z)
VALUES (?, ?, ?, ?)
RETURNING id, flow_id, x, y, z
`

type CreatePlantSiteParams struct {
	FlowID int64
	X      int64
	Y      int64
	Z      int64
}

func (q *Queries) CreatePlantSite(ctx context.Context, arg CreatePlantSiteParams) (PlantSite, error) {
	row := q.db.QueryRowContext(ctx, createPlantSite,
		arg.FlowID,
		arg.X,
		arg.Y,
		arg.Z,
	)
	var i PlantSite
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.X,
		&i.Y,
		&i.Z,
	)
	return i, err
}

const createPlantSiteLux = `-- name: CreatePlantSiteLux :exec
INSERT INTO plant_site_lux (plant_site_id, lux)
VALUES (?, ?)
`

type CreatePlantSiteLuxParams struct {
	PlantSiteID int64
	Lux         int64
}

func (q *Queries) CreatePlantSiteLux(ctx context.Context, arg CreatePlantSiteLuxParams) error {
	_, err := q.db.ExecContext(ctx, createPlantSiteLux, arg.PlantSiteID, arg.Lux)
	return err
}

const createPlantSiteNote = `-- name: CreatePlantSiteNote :one
INSERT INTO plant_site_note (plant_site_id, timestamp, content)
VALUES (?, ?, ?)
RETURNING id, plant_site_id, timestamp, content
`

type CreatePlantSiteNoteParams struct {
	PlantSiteID int64
	Timestamp   time.Time
	Content     sql.NullString
}

func (q *Queries) CreatePlantSiteNote(ctx context.Context, arg CreatePlantSiteNoteParams) (PlantSiteNote, error) {
	row := q.db.QueryRowContext(ctx, createPlantSiteNote, arg.PlantSiteID, arg.Timestamp, arg.Content)
	var i PlantSiteNote
	err := row.Scan(
		&i.ID,
		&i.PlantSiteID,
		&i.Timestamp,
		&i.Content,
	)
	return i, err
}

const createPlantSpecies = `-- name: CreatePlantSpecies :one
INSERT INTO plant_species (name, plant_genus_id)
VALUES (?, ?)
RETURNING id, name, plant_genus_id
`

type CreatePlantSpeciesParams struct {
	Name         string
	PlantGenusID sql.NullInt64
}

func (q *Queries) CreatePlantSpecies(ctx context.Context, arg CreatePlantSpeciesParams) (PlantSpecy, error) {
	row := q.db.QueryRowContext(ctx, createPlantSpecies, arg.Name, arg.PlantGenusID)
	var i PlantSpecy
	err := row.Scan(&i.ID, &i.Name, &i.PlantGenusID)
	return i, err
}

const createSystem = `-- name: CreateSystem :one
INSERT INTO system (name, enclosure_id)
VALUES (?, ?)
RETURNING id, name, enclosure_id
`

type CreateSystemParams struct {
	Name        string
	EnclosureID int64
}

func (q *Queries) CreateSystem(ctx context.Context, arg CreateSystemParams) (System, error) {
	row := q.db.QueryRowContext(ctx, createSystem, arg.Name, arg.EnclosureID)
	var i System
	err := row.Scan(&i.ID, &i.Name, &i.EnclosureID)
	return i, err
}

const createSystemEC = `-- name: CreateSystemEC :exec
INSERT INTO system_ec (system_id, ec)
VALUES (?, ?)
`

type CreateSystemECParams struct {
	SystemID int64
	Ec       float64
}

func (q *Queries) CreateSystemEC(ctx context.Context, arg CreateSystemECParams) error {
	_, err := q.db.ExecContext(ctx, createSystemEC, arg.SystemID, arg.Ec)
	return err
}

const createSystemNote = `-- name: CreateSystemNote :one
INSERT INTO system_note (timestamp, content)
VALUES (?, ?)
RETURNING id, timestamp, content
`

type CreateSystemNoteParams struct {
	Timestamp sql.NullTime
	Content   sql.NullString
}

func (q *Queries) CreateSystemNote(ctx context.Context, arg CreateSystemNoteParams) (SystemNote, error) {
	row := q.db.QueryRowContext(ctx, createSystemNote, arg.Timestamp, arg.Content)
	var i SystemNote
	err := row.Scan(&i.ID, &i.Timestamp, &i.Content)
	return i, err
}

const createSystemOxygen = `-- name: CreateSystemOxygen :exec
INSERT INTO system_oxygen (system_id, oxygen)
VALUES (?, ?)
`

type CreateSystemOxygenParams struct {
	SystemID int64
	Oxygen   float64
}

func (q *Queries) CreateSystemOxygen(ctx context.Context, arg CreateSystemOxygenParams) error {
	_, err := q.db.ExecContext(ctx, createSystemOxygen, arg.SystemID, arg.Oxygen)
	return err
}

const createSystemPH = `-- name: CreateSystemPH :exec
INSERT INTO system_ph (system_id, ph)
VALUES (?, ?)
`

type CreateSystemPHParams struct {
	SystemID int64
	Ph       float64
}

func (q *Queries) CreateSystemPH(ctx context.Context, arg CreateSystemPHParams) error {
	_, err := q.db.ExecContext(ctx, createSystemPH, arg.SystemID, arg.Ph)
	return err
}

const createSystemWaterProximity = `-- name: CreateSystemWaterProximity :exec
INSERT INTO system_water_proximity (system_id, proximity_m)
VALUES (?, ?)
`

type CreateSystemWaterProximityParams struct {
	SystemID   int64
	ProximityM float64
}

func (q *Queries) CreateSystemWaterProximity(ctx context.Context, arg CreateSystemWaterProximityParams) error {
	_, err := q.db.ExecContext(ctx, createSystemWaterProximity, arg.SystemID, arg.ProximityM)
	return err
}

const createSystemWaterTemperature = `-- name: CreateSystemWaterTemperature :exec
INSERT INTO system_water_temperature (system_id, water_temperature_c)
VALUES (?, ?)
`

type CreateSystemWaterTemperatureParams struct {
	SystemID          int64
	WaterTemperatureC float64
}

func (q *Queries) CreateSystemWaterTemperature(ctx context.Context, arg CreateSystemWaterTemperatureParams) error {
	_, err := q.db.ExecContext(ctx, createSystemWaterTemperature, arg.SystemID, arg.WaterTemperatureC)
	return err
}

const deleteEnclosure = `-- name: DeleteEnclosure :exec
DELETE FROM enclosure WHERE id = ?
`

func (q *Queries) DeleteEnclosure(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnclosure, id)
	return err
}

const deleteEnclosureNote = `-- name: DeleteEnclosureNote :exec
DELETE FROM enclosure_note WHERE id = ?
`

func (q *Queries) DeleteEnclosureNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnclosureNote, id)
	return err
}

const deleteFlow = `-- name: DeleteFlow :exec
DELETE FROM flow WHERE id = ?
`

func (q *Queries) DeleteFlow(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFlow, id)
	return err
}

const deleteFlowNote = `-- name: DeleteFlowNote :exec
DELETE FROM flow_note WHERE id = ?
`

func (q *Queries) DeleteFlowNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFlowNote, id)
	return err
}

const deletePlant = `-- name: DeletePlant :exec
DELETE FROM plant WHERE id = ?
`

func (q *Queries) DeletePlant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlant, id)
	return err
}

const deletePlantGenus = `-- name: DeletePlantGenus :exec
DELETE FROM plant_genus WHERE id = ?
`

func (q *Queries) DeletePlantGenus(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlantGenus, id)
	return err
}

const deletePlantNote = `-- name: DeletePlantNote :exec
DELETE FROM plant_note WHERE id = ?
`

func (q *Queries) DeletePlantNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlantNote, id)
	return err
}

const deletePlantSite = `-- name: DeletePlantSite :exec
DELETE FROM plant_site WHERE id = ?
`

func (q *Queries) DeletePlantSite(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlantSite, id)
	return err
}

const deletePlantSiteNote = `-- name: DeletePlantSiteNote :exec
DELETE FROM plant_site_note WHERE id = ?
`

func (q *Queries) DeletePlantSiteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlantSiteNote, id)
	return err
}

const deletePlantSpecies = `-- name: DeletePlantSpecies :exec
DELETE FROM plant_species WHERE id = ?
`

func (q *Queries) DeletePlantSpecies(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlantSpecies, id)
	return err
}

const deleteSystem = `-- name: DeleteSystem :exec
DELETE FROM system WHERE id = ?
`

func (q *Queries) DeleteSystem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSystem, id)
	return err
}

const deleteSystemNote = `-- name: DeleteSystemNote :exec
DELETE FROM system_note WHERE id = ?
`

func (q *Queries) DeleteSystemNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSystemNote, id)
	return err
}

const getEnclosure = `-- name: GetEnclosure :one
SELECT id, name FROM enclosure WHERE id=? LIMIT 1
`

func (q *Queries) GetEnclosure(ctx context.Context, id int64) (Enclosure, error) {
	row := q.db.QueryRowContext(ctx, getEnclosure, id)
	var i Enclosure
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getEnclosureNote = `-- name: GetEnclosureNote :one
SELECT id, timestamp, content FROM enclosure_note WHERE id=? LIMIT 1
`

func (q *Queries) GetEnclosureNote(ctx context.Context, id int64) (EnclosureNote, error) {
	row := q.db.QueryRowContext(ctx, getEnclosureNote, id)
	var i EnclosureNote
	err := row.Scan(&i.ID, &i.Timestamp, &i.Content)
	return i, err
}

const getFlow = `-- name: GetFlow :one
SELECT id, name, system_id, parent_flow_id FROM flow WHERE id=? LIMIT 1
`

func (q *Queries) GetFlow(ctx context.Context, id int64) (Flow, error) {
	row := q.db.QueryRowContext(ctx, getFlow, id)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SystemID,
		&i.ParentFlowID,
	)
	return i, err
}

const getFlowNote = `-- name: GetFlowNote :one
SELECT id, timestamp, content FROM flow_note WHERE id=? LIMIT 1
`

func (q *Queries) GetFlowNote(ctx context.Context, id int64) (FlowNote, error) {
	row := q.db.QueryRowContext(ctx, getFlowNote, id)
	var i FlowNote
	err := row.Scan(&i.ID, &i.Timestamp, &i.Content)
	return i, err
}

const getPlant = `-- name: GetPlant :one
SELECT id, plant_site_id, planted_on, species_id FROM plant WHERE id=? LIMIT 1
`

func (q *Queries) GetPlant(ctx context.Context, id int64) (Plant, error) {
	row := q.db.QueryRowContext(ctx, getPlant, id)
	var i Plant
	err := row.Scan(
		&i.ID,
		&i.PlantSiteID,
		&i.PlantedOn,
		&i.SpeciesID,
	)
	return i, err
}

const getPlantGenus = `-- name: GetPlantGenus :one
SELECT id, name FROM plant_genus WHERE id=? LIMIT 1
`

func (q *Queries) GetPlantGenus(ctx context.Context, id int64) (PlantGenu, error) {
	row := q.db.QueryRowContext(ctx, getPlantGenus, id)
	var i PlantGenu
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPlantNote = `-- name: GetPlantNote :one
SELECT id, plan_id, timestamp, content FROM plant_note WHERE id=? LIMIT 1
`

func (q *Queries) GetPlantNote(ctx context.Context, id int64) (PlantNote, error) {
	row := q.db.QueryRowContext(ctx, getPlantNote, id)
	var i PlantNote
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Timestamp,
		&i.Content,
	)
	return i, err
}

const getPlantSite = `-- name: GetPlantSite :one
SELECT id, flow_id, x, y, z FROM plant_site WHERE id=? LIMIT 1
`

func (q *Queries) GetPlantSite(ctx context.Context, id int64) (PlantSite, error) {
	row := q.db.QueryRowContext(ctx, getPlantSite, id)
	var i PlantSite
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.X,
		&i.Y,
		&i.Z,
	)
	return i, err
}

const getPlantSiteNote = `-- name: GetPlantSiteNote :one
SELECT id, plant_site_id, timestamp, content FROM plant_site_note WHERE id=? LIMIT 1
`

func (q *Queries) GetPlantSiteNote(ctx context.Context, id int64) (PlantSiteNote, error) {
	row := q.db.QueryRowContext(ctx, getPlantSiteNote, id)
	var i PlantSiteNote
	err := row.Scan(
		&i.ID,
		&i.PlantSiteID,
		&i.Timestamp,
		&i.Content,
	)
	return i, err
}

const getPlantSpecies = `-- name: GetPlantSpecies :one
SELECT id, name, plant_genus_id FROM plant_species WHERE id=? LIMIT 1
`

func (q *Queries) GetPlantSpecies(ctx context.Context, id int64) (PlantSpecy, error) {
	row := q.db.QueryRowContext(ctx, getPlantSpecies, id)
	var i PlantSpecy
	err := row.Scan(&i.ID, &i.Name, &i.PlantGenusID)
	return i, err
}

const getSystem = `-- name: GetSystem :one
SELECT id, name, enclosure_id FROM system WHERE id=? LIMIT 1
`

func (q *Queries) GetSystem(ctx context.Context, id int64) (System, error) {
	row := q.db.QueryRowContext(ctx, getSystem, id)
	var i System
	err := row.Scan(&i.ID, &i.Name, &i.EnclosureID)
	return i, err
}

const getSystemNote = `-- name: GetSystemNote :one
SELECT id, timestamp, content FROM system_note WHERE id=? LIMIT 1
`

func (q *Queries) GetSystemNote(ctx context.Context, id int64) (SystemNote, error) {
	row := q.db.QueryRowContext(ctx, getSystemNote, id)
	var i SystemNote
	err := row.Scan(&i.ID, &i.Timestamp, &i.Content)
	return i, err
}

const listChildFlows = `-- name: ListChildFlows :many
SELECT id, name, system_id, parent_flow_id FROM flow WHERE parent_flow_id = ?
`

func (q *Queries) ListChildFlows(ctx context.Context, parentFlowID sql.NullInt64) ([]Flow, error) {
	rows, err := q.db.QueryContext(ctx, listChildFlows, parentFlowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SystemID,
			&i.ParentFlowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnclosureAirHumidity = `-- name: ListEnclosureAirHumidity :many
SELECT id, timestamp, enclosure_id, humidity_rh FROM enclosure_air_humidity
WHERE enclosure_id = ?
ORDER BY timestamp DESC
LIMIT ?
`

type ListEnclosureAirHumidityParams struct {
	EnclosureID int64
	Limit       int64
}

func (q *Queries) ListEnclosureAirHumidity(ctx context.Context, arg ListEnclosureAirHumidityParams) ([]EnclosureAirHumidity, error) {
	rows, err := q.db.QueryContext(ctx, listEnclosureAirHumidity, arg.EnclosureID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnclosureAirHumidity
	for rows.Next() {
		var i EnclosureAirHumidity
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.EnclosureID,
			&i.HumidityRh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnclosureAirTemperatures = `-- name: ListEnclosureAirTemperatures :many
SELECT id, timestamp, enclosure_id, temperature_c FROM enclosure_air_temperature
WHERE enclosure_id = ?
ORDER BY timestamp DESC
LIMIT ?
`

type ListEnclosureAirTemperaturesParams struct {
	EnclosureID int64
	Limit       int64
}

func (q *Queries) ListEnclosureAirTemperatures(ctx context.Context, arg ListEnclosureAirTemperaturesParams) ([]EnclosureAirTemperature, error) {
	rows, err := q.db.QueryContext(ctx, listEnclosureAirTemperatures, arg.EnclosureID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnclosureAirTemperature
	for rows.Next() {
		var i EnclosureAirTemperature
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.EnclosureID,
			&i.TemperatureC,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnclosureNotes = `-- name: ListEnclosureNotes :many
SELECT id, timestamp, content FROM enclosure_note
`

func (q *Queries) ListEnclosureNotes(ctx context.Context) ([]EnclosureNote, error) {
	rows, err := q.db.QueryContext(ctx, listEnclosureNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnclosureNote
	for rows.Next() {
		var i EnclosureNote
		if err := rows.Scan(&i.ID, &i.Timestamp, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnclosurePlants = `-- name: ListEnclosurePlants :many
SELECT plant.id            as id,
       plant.planted_on    as planted_on,
       plant.plant_site_id as plant_site_id,
       plant_site.x        as x,
       plant_site.y        as y,
       plant_site.z        as z,
       flow.id             as flow_id,
       flow.name           as flow_name
    FROM plant
    LEFT JOIN plant_site ON plant_site.id = plant.plant_site_id
    LEFT JOIN flow ON flow.id = plant_site.flow_id
    WHERE plant_site.flow_id IN (
        SELECT id FROM flow WHERE system_id IN (
            SELECT id FROM system WHERE enclosure_id = ?
        )
    )
`

type ListEnclosurePlantsRow struct {
	ID          int64
	PlantedOn   sql.NullTime
	PlantSiteID int64
	X           sql.NullInt64
	Y           sql.NullInt64
	Z           sql.NullInt64
	FlowID      sql.NullInt64
	FlowName    sql.NullString
}

func (q *Queries) ListEnclosurePlants(ctx context.Context, enclosureID int64) ([]ListEnclosurePlantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnclosurePlants, enclosureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnclosurePlantsRow
	for rows.Next() {
		var i ListEnclosurePlantsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlantedOn,
			&i.PlantSiteID,
			&i.X,
			&i.Y,
			&i.Z,
			&i.FlowID,
			&i.FlowName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnclosures = `-- name: ListEnclosures :many
SELECT id, name FROM enclosure
`

func (q *Queries) ListEnclosures(ctx context.Context) ([]Enclosure, error) {
	rows, err := q.db.QueryContext(ctx, listEnclosures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enclosure
	for rows.Next() {
		var i Enclosure
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowNotes = `-- name: ListFlowNotes :many
SELECT id, timestamp, content FROM flow_note
`

func (q *Queries) ListFlowNotes(ctx context.Context) ([]FlowNote, error) {
	rows, err := q.db.QueryContext(ctx, listFlowNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowNote
	for rows.Next() {
		var i FlowNote
		if err := rows.Scan(&i.ID, &i.Timestamp, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowPlants = `-- name: ListFlowPlants :many
SELECT plant.id            as id,
       plant.planted_on    as planted_on,
       plant.plant_site_id as plant_site_id,
       plant_site.x        as x,
       plant_site.y        as y,
       plant_site.z        as z,
       flow.name as flow_name,
       flow.id as flow_id
    FROM plant
    LEFT JOIN plant_site ON plant_site.id = plant.plant_site_id
    INNER JOIN flow ON flow.id = plant_site.flow_id
    WHERE plant_site.flow_id = ?
`

type ListFlowPlantsRow struct {
	ID          int64
	PlantedOn   sql.NullTime
	PlantSiteID int64
	X           sql.NullInt64
	Y           sql.NullInt64
	Z           sql.NullInt64
	FlowName    string
	FlowID      int64
}

func (q *Queries) ListFlowPlants(ctx context.Context, flowID int64) ([]ListFlowPlantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlowPlants, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowPlantsRow
	for rows.Next() {
		var i ListFlowPlantsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlantedOn,
			&i.PlantSiteID,
			&i.X,
			&i.Y,
			&i.Z,
			&i.FlowName,
			&i.FlowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlows = `-- name: ListFlows :many
SELECT id, name, system_id, parent_flow_id FROM flow
`

func (q *Queries) ListFlows(ctx context.Context) ([]Flow, error) {
	rows, err := q.db.QueryContext(ctx, listFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SystemID,
			&i.ParentFlowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsBySystem = `-- name: ListFlowsBySystem :many
SELECT id, name, system_id, parent_flow_id FROM flow WHERE system_id = ?
`

func (q *Queries) ListFlowsBySystem(ctx context.Context, systemID int64) ([]Flow, error) {
	rows, err := q.db.QueryContext(ctx, listFlowsBySystem, systemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SystemID,
			&i.ParentFlowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantGenera = `-- name: ListPlantGenera :many
SELECT id, name FROM plant_genus
`

func (q *Queries) ListPlantGenera(ctx context.Context) ([]PlantGenu, error) {
	rows, err := q.db.QueryContext(ctx, listPlantGenera)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantGenu
	for rows.Next() {
		var i PlantGenu
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantNotes = `-- name: ListPlantNotes :many
SELECT id, plan_id, timestamp, content FROM plant_note
`

func (q *Queries) ListPlantNotes(ctx context.Context) ([]PlantNote, error) {
	rows, err := q.db.QueryContext(ctx, listPlantNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantNote
	for rows.Next() {
		var i PlantNote
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Timestamp,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantNotesByPlant = `-- name: ListPlantNotesByPlant :many
SELECT id, plan_id, timestamp, content FROM plant_note WHERE plan_id = ?
`

func (q *Queries) ListPlantNotesByPlant(ctx context.Context, planID sql.NullInt64) ([]PlantNote, error) {
	rows, err := q.db.QueryContext(ctx, listPlantNotesByPlant, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantNote
	for rows.Next() {
		var i PlantNote
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Timestamp,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantSiteNotes = `-- name: ListPlantSiteNotes :many
SELECT id, plant_site_id, timestamp, content FROM plant_site_note
`

func (q *Queries) ListPlantSiteNotes(ctx context.Context) ([]PlantSiteNote, error) {
	rows, err := q.db.QueryContext(ctx, listPlantSiteNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantSiteNote
	for rows.Next() {
		var i PlantSiteNote
		if err := rows.Scan(
			&i.ID,
			&i.PlantSiteID,
			&i.Timestamp,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantSiteNotesBySite = `-- name: ListPlantSiteNotesBySite :many
SELECT id, plant_site_id, timestamp, content FROM plant_site_note WHERE plant_site_id = ?
`

func (q *Queries) ListPlantSiteNotesBySite(ctx context.Context, plantSiteID int64) ([]PlantSiteNote, error) {
	rows, err := q.db.QueryContext(ctx, listPlantSiteNotesBySite, plantSiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantSiteNote
	for rows.Next() {
		var i PlantSiteNote
		if err := rows.Scan(
			&i.ID,
			&i.PlantSiteID,
			&i.Timestamp,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantSites = `-- name: ListPlantSites :many
SELECT id, flow_id, x, y, z FROM plant_site
`

func (q *Queries) ListPlantSites(ctx context.Context) ([]PlantSite, error) {
	rows, err := q.db.QueryContext(ctx, listPlantSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantSite
	for rows.Next() {
		var i PlantSite
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.X,
			&i.Y,
			&i.Z,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantSitesByFlow = `-- name: ListPlantSitesByFlow :many
SELECT id, flow_id, x, y, z FROM plant_site WHERE flow_id = ?
`

func (q *Queries) ListPlantSitesByFlow(ctx context.Context, flowID int64) ([]PlantSite, error) {
	rows, err := q.db.QueryContext(ctx, listPlantSitesByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantSite
	for rows.Next() {
		var i PlantSite
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.X,
			&i.Y,
			&i.Z,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantSpecies = `-- name: ListPlantSpecies :many
SELECT id, name, plant_genus_id FROM plant_species
`

func (q *Queries) ListPlantSpecies(ctx context.Context) ([]PlantSpecy, error) {
	rows, err := q.db.QueryContext(ctx, listPlantSpecies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantSpecy
	for rows.Next() {
		var i PlantSpecy
		if err := rows.Scan(&i.ID, &i.Name, &i.PlantGenusID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantSpeciesByGenus = `-- name: ListPlantSpeciesByGenus :many
SELECT id, name, plant_genus_id FROM plant_species WHERE plant_genus_id = ?
`

func (q *Queries) ListPlantSpeciesByGenus(ctx context.Context, plantGenusID sql.NullInt64) ([]PlantSpecy, error) {
	rows, err := q.db.QueryContext(ctx, listPlantSpeciesByGenus, plantGenusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantSpecy
	for rows.Next() {
		var i PlantSpecy
		if err := rows.Scan(&i.ID, &i.Name, &i.PlantGenusID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlants = `-- name: ListPlants :many
SELECT id, plant_site_id, planted_on, species_id FROM plant
`

func (q *Queries) ListPlants(ctx context.Context) ([]Plant, error) {
	rows, err := q.db.QueryContext(ctx, listPlants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plant
	for rows.Next() {
		var i Plant
		if err := rows.Scan(
			&i.ID,
			&i.PlantSiteID,
			&i.PlantedOn,
			&i.SpeciesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantsBySite = `-- name: ListPlantsBySite :many
SELECT id, plant_site_id, planted_on, species_id FROM plant WHERE plant_site_id = ?
`

func (q *Queries) ListPlantsBySite(ctx context.Context, plantSiteID int64) ([]Plant, error) {
	rows, err := q.db.QueryContext(ctx, listPlantsBySite, plantSiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plant
	for rows.Next() {
		var i Plant
		if err := rows.Scan(
			&i.ID,
			&i.PlantSiteID,
			&i.PlantedOn,
			&i.SpeciesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantsBySpecies = `-- name: ListPlantsBySpecies :many
SELECT id, plant_site_id, planted_on, species_id FROM plant WHERE species_id = ?
`

func (q *Queries) ListPlantsBySpecies(ctx context.Context, speciesID sql.NullInt64) ([]Plant, error) {
	rows, err := q.db.QueryContext(ctx, listPlantsBySpecies, speciesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plant
	for rows.Next() {
		var i Plant
		if err := rows.Scan(
			&i.ID,
			&i.PlantSiteID,
			&i.PlantedOn,
			&i.SpeciesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemEC = `-- name: ListSystemEC :many
SELECT id, system_id, timestamp, ec FROM system_ec
WHERE system_id = ?
ORDER BY timestamp DESC
LIMIT ?
`

type ListSystemECParams struct {
	SystemID int64
	Limit    int64
}

func (q *Queries) ListSystemEC(ctx context.Context, arg ListSystemECParams) ([]SystemEc, error) {
	rows, err := q.db.QueryContext(ctx, listSystemEC, arg.SystemID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemEc
	for rows.Next() {
		var i SystemEc
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.Timestamp,
			&i.Ec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemNotes = `-- name: ListSystemNotes :many
SELECT id, timestamp, content FROM system_note
`

func (q *Queries) ListSystemNotes(ctx context.Context) ([]SystemNote, error) {
	rows, err := q.db.QueryContext(ctx, listSystemNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemNote
	for rows.Next() {
		var i SystemNote
		if err := rows.Scan(&i.ID, &i.Timestamp, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemPH = `-- name: ListSystemPH :many
SELECT id, system_id, timestamp, ph FROM system_ph
WHERE system_id = ?
ORDER BY timestamp DESC
LIMIT ?
`

type ListSystemPHParams struct {
	SystemID int64
	Limit    int64
}

func (q *Queries) ListSystemPH(ctx context.Context, arg ListSystemPHParams) ([]SystemPh, error) {
	rows, err := q.db.QueryContext(ctx, listSystemPH, arg.SystemID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemPh
	for rows.Next() {
		var i SystemPh
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.Timestamp,
			&i.Ph,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemWaterTemperature = `-- name: ListSystemWaterTemperature :many
SELECT id, system_id, timestamp, water_temperature_c FROM system_water_temperature
WHERE system_id = ?
ORDER BY timestamp DESC
LIMIT ?
`

type ListSystemWaterTemperatureParams struct {
	SystemID int64
	Limit    int64
}

func (q *Queries) ListSystemWaterTemperature(ctx context.Context, arg ListSystemWaterTemperatureParams) ([]SystemWaterTemperature, error) {
	rows, err := q.db.QueryContext(ctx, listSystemWaterTemperature, arg.SystemID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemWaterTemperature
	for rows.Next() {
		var i SystemWaterTemperature
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.Timestamp,
			&i.WaterTemperatureC,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystems = `-- name: ListSystems :many
SELECT id, name, enclosure_id FROM system
`

func (q *Queries) ListSystems(ctx context.Context) ([]System, error) {
	rows, err := q.db.QueryContext(ctx, listSystems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []System
	for rows.Next() {
		var i System
		if err := rows.Scan(&i.ID, &i.Name, &i.EnclosureID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemsByEnclosure = `-- name: ListSystemsByEnclosure :many
SELECT id, name, enclosure_id FROM system WHERE enclosure_id = ?
`

func (q *Queries) ListSystemsByEnclosure(ctx context.Context, enclosureID int64) ([]System, error) {
	rows, err := q.db.QueryContext(ctx, listSystemsByEnclosure, enclosureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []System
	for rows.Next() {
		var i System
		if err := rows.Scan(&i.ID, &i.Name, &i.EnclosureID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnclosure = `-- name: UpdateEnclosure :one
UPDATE enclosure
SET name = ?
WHERE id = ?
RETURNING id, name
`

type UpdateEnclosureParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateEnclosure(ctx context.Context, arg UpdateEnclosureParams) (Enclosure, error) {
	row := q.db.QueryRowContext(ctx, updateEnclosure, arg.Name, arg.ID)
	var i Enclosure
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateEnclosureNote = `-- name: UpdateEnclosureNote :one
UPDATE enclosure_note
SET timestamp = ?, content = ?
WHERE id = ?
RETURNING id, timestamp, content
`

type UpdateEnclosureNoteParams struct {
	Timestamp sql.NullTime
	Content   sql.NullString
	ID        int64
}

func (q *Queries) UpdateEnclosureNote(ctx context.Context, arg UpdateEnclosureNoteParams) (EnclosureNote, error) {
	row := q.db.QueryRowContext(ctx, updateEnclosureNote, arg.Timestamp, arg.Content, arg.ID)
	var i EnclosureNote
	err := row.Scan(&i.ID, &i.Timestamp, &i.Content)
	return i, err
}

const updateFlow = `-- name: UpdateFlow :one
UPDATE flow
SET name = ?, system_id = ?, parent_flow_id = ?
WHERE id = ?
RETURNING id, name, system_id, parent_flow_id
`

type UpdateFlowParams struct {
	Name         string
	SystemID     int64
	ParentFlowID sql.NullInt64
	ID           int64
}

func (q *Queries) UpdateFlow(ctx context.Context, arg UpdateFlowParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, updateFlow,
		arg.Name,
		arg.SystemID,
		arg.ParentFlowID,
		arg.ID,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SystemID,
		&i.ParentFlowID,
	)
	return i, err
}

const updateFlowNote = `-- name: UpdateFlowNote :one
UPDATE flow_note
SET timestamp = ?, content = ?
WHERE id = ?
RETURNING id, timestamp, content
`

type UpdateFlowNoteParams struct {
	Timestamp sql.NullTime
	Content   sql.NullString
	ID        int64
}

func (q *Queries) UpdateFlowNote(ctx context.Context, arg UpdateFlowNoteParams) (FlowNote, error) {
	row := q.db.QueryRowContext(ctx, updateFlowNote, arg.Timestamp, arg.Content, arg.ID)
	var i FlowNote
	err := row.Scan(&i.ID, &i.Timestamp, &i.Content)
	return i, err
}

const updatePlant = `-- name: UpdatePlant :one
UPDATE plant
SET plant_site_id = ?, planted_on = ?, species_id = ?
WHERE id = ?
RETURNING id, plant_site_id, planted_on, species_id
`

type UpdatePlantParams struct {
	PlantSiteID int64
	PlantedOn   sql.NullTime
	SpeciesID   sql.NullInt64
	ID          int64
}

func (q *Queries) UpdatePlant(ctx context.Context, arg UpdatePlantParams) (Plant, error) {
	row := q.db.QueryRowContext(ctx, updatePlant,
		arg.PlantSiteID,
		arg.PlantedOn,
		arg.SpeciesID,
		arg.ID,
	)
	var i Plant
	err := row.Scan(
		&i.ID,
		&i.PlantSiteID,
		&i.PlantedOn,
		&i.SpeciesID,
	)
	return i, err
}

const updatePlantGenus = `-- name: UpdatePlantGenus :one
UPDATE plant_genus
SET name = ?
WHERE id = ?
RETURNING id, name
`

type UpdatePlantGenusParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdatePlantGenus(ctx context.Context, arg UpdatePlantGenusParams) (PlantGenu, error) {
	row := q.db.QueryRowContext(ctx, updatePlantGenus, arg.Name, arg.ID)
	var i PlantGenu
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updatePlantNote = `-- name: UpdatePlantNote :one
UPDATE plant_note
SET plan_id = ?, timestamp = ?, content = ?
WHERE id = ?
RETURNING id, plan_id, timestamp, content
`

type UpdatePlantNoteParams struct {
	PlanID    sql.NullInt64
	Timestamp time.Time
	Content   sql.NullString
	ID        int64
}

func (q *Queries) UpdatePlantNote(ctx context.Context, arg UpdatePlantNoteParams) (PlantNote, error) {
	row := q.db.QueryRowContext(ctx, updatePlantNote,
		arg.PlanID,
		arg.Timestamp,
		arg.Content,
		arg.ID,
	)
	var i PlantNote
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Timestamp,
		&i.Content,
	)
	return i, err
}

const updatePlantSite = `-- name: UpdatePlantSite :one
UPDATE plant_site
SET flow_id = ?, x = ?, y = ?, z = ?
WHERE id = ?
RETURNING id, flow_id, x, y, z
`

type UpdatePlantSiteParams struct {
	FlowID int64
	X      int64
	Y      int64
	Z      int64
	ID     int64
}

func (q *Queries) UpdatePlantSite(ctx context.Context, arg UpdatePlantSiteParams) (PlantSite, error) {
	row := q.db.QueryRowContext(ctx, updatePlantSite,
		arg.FlowID,
		arg.X,
		arg.Y,
		arg.Z,
		arg.ID,
	)
	var i PlantSite
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.X,
		&i.Y,
		&i.Z,
	)
	return i, err
}

const updatePlantSiteNote = `-- name: UpdatePlantSiteNote :one
UPDATE plant_site_note
SET plant_site_id = ?, timestamp = ?, content = ?
WHERE id = ?
RETURNING id, plant_site_id, timestamp, content
`

type UpdatePlantSiteNoteParams struct {
	PlantSiteID int64
	Timestamp   time.Time
	Content     sql.NullString
	ID          int64
}

func (q *Queries) UpdatePlantSiteNote(ctx context.Context, arg UpdatePlantSiteNoteParams) (PlantSiteNote, error) {
	row := q.db.QueryRowContext(ctx, updatePlantSiteNote,
		arg.PlantSiteID,
		arg.Timestamp,
		arg.Content,
		arg.ID,
	)
	var i PlantSiteNote
	err := row.Scan(
		&i.ID,
		&i.PlantSiteID,
		&i.Timestamp,
		&i.Content,
	)
	return i, err
}

const updatePlantSpecies = `-- name: UpdatePlantSpecies :one
UPDATE plant_species
SET name = ?, plant_genus_id = ?
WHERE id = ?
RETURNING id, name, plant_genus_id
`

type UpdatePlantSpeciesParams struct {
	Name         string
	PlantGenusID sql.NullInt64
	ID           int64
}

func (q *Queries) UpdatePlantSpecies(ctx context.Context, arg UpdatePlantSpeciesParams) (PlantSpecy, error) {
	row := q.db.QueryRowContext(ctx, updatePlantSpecies, arg.Name, arg.PlantGenusID, arg.ID)
	var i PlantSpecy
	err := row.Scan(&i.ID, &i.Name, &i.PlantGenusID)
	return i, err
}

const updateSystem = `-- name: UpdateSystem :one
UPDATE system
SET name = ?, enclosure_id = ?
WHERE id = ?
RETURNING id, name, enclosure_id
`

type UpdateSystemParams struct {
	Name        string
	EnclosureID int64
	ID          int64
}

func (q *Queries) UpdateSystem(ctx context.Context, arg UpdateSystemParams) (System, error) {
	row := q.db.QueryRowContext(ctx, updateSystem, arg.Name, arg.EnclosureID, arg.ID)
	var i System
	err := row.Scan(&i.ID, &i.Name, &i.EnclosureID)
	return i, err
}

const updateSystemNote = `-- name: UpdateSystemNote :one
UPDATE system_note
SET timestamp = ?, content = ?
WHERE id = ?
RETURNING id, timestamp, content
`

type UpdateSystemNoteParams struct {
	Timestamp sql.NullTime
	Content   sql.NullString
	ID        int64
}

func (q *Queries) UpdateSystemNote(ctx context.Context, arg UpdateSystemNoteParams) (SystemNote, error) {
	row := q.db.QueryRowContext(ctx, updateSystemNote, arg.Timestamp, arg.Content, arg.ID)
	var i SystemNote
	err := row.Scan(&i.ID, &i.Timestamp, &i.Content)
	return i, err
}
